apiVersion: apps/v1
kind: Deployment
metadata:
  name: newstracker
  labels:
    app: newstracker
spec:
  selector:
    matchLabels:
      app: newstracker
  template:
    metadata:
      labels:
        app: newstracker
    spec:
      containers:
        - name: newstracker
          image: pranauvs/newstracker:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: newstracker
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: newstracker
  type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newstracker
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
 rules:
  - http:
     paths: 
       - backend:
           service:
             name: newstracker-service
             port:
              number: 5000
         path: /
         pathType: Prefix

